version: '2'
services:

  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
  dummy:
    image: bash
    command: ["ping" , "dockerhost"]

  tomcat-1:
    image: tomcat:latest
    hostname: tomcat-1
    ports:
      - "18080:8080"
    environment:
      JAVA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"
    volumes:
      - ../jolokia:/opt/jolokia

  tomcat-2:
    image: tomcat:latest
    hostname: tomcat-2
    ports:
      - "18081:8080"
    environment:
      JAVA_OPTS: "-javaagent:/opt/jolokia/jolokia-jvm-1.6.0-agent.jar=port=8778,host=0.0.0.0"
    volumes:
      - ../jolokia:/opt/jolokia

  telegraf:
    image: telegraf:latest
    restart: always
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
      SPLUNK_HEC_URL: "https://dockerhost:8088"
      SPLUNK_HEC_TOKEN: "205d43f1-2a31-4e60-a8b3-327eda49944a"
    hostname: telegraf
    depends_on:
      - tomcat-1
    volumes:
      - ../telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
